global:
  proxy:
    autoInject: disabled
  omitSidecarInjectorConfigMap: false

meshConfig:
  enableTracing: false
  enableAutoMtls: false

pilot:
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits: ~
