{{- if and .Values.merlin.imageBuilder.serviceAccount .Values.merlin.imageBuilder.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.merlin.imageBuilder.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.merlin.imageBuilder.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.merlin.imageBuilder.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.merlin.imageBuilder.serviceAccount.labels }}
    {{- toYaml .Values.merlin.imageBuilder.serviceAccount.labels | nindent 4 }}
    {{- end }}
{{ end }}
