apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mlflow.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.podLabels}}
    {{ toYaml .Values.podLabels | nindent 4 }}
  {{- end}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mlflow.fullname" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ template "mlflow.fullname" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podLabels}}
        {{ toYaml .Values.podLabels | nindent 8 }}
      {{- end}}
    spec:
      containers:
      - name: {{ template "mlflow.fullname" . }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: "http"
        livenessProbe:
          httpGet:
            path: {{ default "/api/2.0/mlflow/experiments/list" .Values.livenessProbe.path }}
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ default "/api/2.0/mlflow/experiments/list" .Values.readinessProbe.path }}
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: BACKEND_STORE_URI
          value: "{{ template "mlflow.backendStoreUri" . }}"
        - name: ARTIFACT_ROOT
          value: "{{ .Values.artifactRoot }}"
        - name: HOST
          value: "{{ .Values.host }}"
        - name: PORT
          value: "{{ .Values.service.internalPort }}"
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
